---

plugins:
  - babel
  - flowtype

env:
  node: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:flowtype/recommended'

rules:
  no-console: 0
  linebreak-style: 0